---
layout: post
title: Quarterly Report
subtitle: Nov 1, 2018 - Jan 31, 2019
---

The Campus Champions program continues to grow at a steady rate (individual members: 539 and institutional members: 277) and Champions continue to actively engage and collaborate not only on our email list, Slack and the AskCI platforms, but also through our regularly scheduled calls and our new “ad hoc call” offerings. Efforts around Grant Proposal Writing Apprenticeship and the Paper Writing Apprenticeship that arose from the Virtual Residency Workshops are on-going. Many Champions attended SC18 and contributed to the larger advanced CI community, but also found time in busy schedules to meet as a community. Champion climate survey results were finalized and shared with the community at our All Champions call. And as 2018 came to a close, Champions finished celebrating our ten year anniversary.

In 2018 Champion staff and volunteer leadership began to utilize the fifth Tuesday of the month for technical workshops on topics such as Markdown, Git and GitHub. These workshops are presented by volunteer members of the community (including Student Champion, Sateesh Peri, who presented in January) and attendance has averaged 50 participants per call. In addition, Champions staff added a new prototype event as part of our effort to bring interesting and relevant technical information to our community with topics typically drawn from discussions on our list or in our community calls. Jeff Pummill assumed responsibility for this effort entitled “Tech Talks” and works with technical experts to bring topics such as EasyBuild and Spack, XDMoD, the GABBs Project and the upcoming Sustainability via On-Campus Teams to our community. This effort is aimed at providing a consistent technical component to the ever growing Champions community, with much of the content to be provided by the Champions themselves.

One of the wonderful things about a community like the Champions is the ability to find a “friendly” face in a sea of strangers. Thanks to our friends at XSEDE, who hosted a “Breakfast with the Champions” at their booth, Champions were able to come together in an informal (but dynamic!) setting to network, meet fellow Champions in person, engage with XSEDE staff as well as potential new Champions, partners and supporters. This was also another great opportunity to celebrate our ten year anniversary! In addition, the Champions held a formal meeting at SC18 on 11/13 (also broadcast virtually for those unable to attend SC18) where we hosted guest speaker Dr. Dan Stanzione who discussed Frontera, describing how NSF’s new leadership class system will operate, as well as an announcement that the project includes direct support for the Champions participating in conferences like PEARC. The meeting also provided another opportunity to network and added visibility of our volunteer leaders, as well as a platform for Champions to provide “flash talks” on everything from system rebuilds with XCRI to new efforts with Women in HPC that might be of interest to other members of the community. 

We wrapped up the Champions Climate Survey review with a presentation of the results to the Leadership Team in November and the full Champions community in December by Lorna Rivera. Generally, staff and leadership are very pleased with the results of the survey. The results showed that Champions are thinking about our sustainable future. With a response rate just over 40%, the general findings of the survey showed that Champions rated their overall experience with the program positively. The results showed that the “Champions community impact extends beyond individual knowledge and skills improvement to institutionalization of the champion role, changes in institutional research computing policy, and inclusion of Champions in strategic talent recruitment for their organizations.” The Champions culture was reported as being equitable and inclusive, with “respondents from non-research-intensive organizations and members of marginalized groups including women and underrepresented racial/ethnic groups in HPC, report positive experiences in the organization that mirror majority respondents.” Other key findings included, that specific resources like the mailing list, peer mentoring and Champions allocations were all seen as critical. In fact, when asked whether the email list has been useful in guiding policy/technology decision at their institutions, 85% respondents said yes. The Regional program, while needing further refinement, was seen as useful for the onboarding of new Champions. 

Finally, the Champions community spent the whole of 2018 celebrating our ten-year anniversary. It was exciting to see the participation and support in various activities (including our 10-year anniversary video, PEARC18 and SC18 activities) as well as actively participate in discussions about the importance of having a community like the Champions and our ongoing efforts to create a sustainable future for the program.
